# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-25 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departamentos',
            table='Censo].[Departamentos',
        ),
        migrations.AlterModelTable(
            name='encuestadores',
            table='Censo].[Encuestadores',
        ),
        migrations.AlterModelTable(
            name='estados',
            table='Censo].[Estados',
        ),
        migrations.AlterModelTable(
            name='fichacenso',
            table='Censo].[FichaCenso',
        ),
        migrations.AlterModelTable(
            name='filiales',
            table='Censo].[Filiales',
        ),
        migrations.AlterModelTable(
            name='hijos',
            table='Censo].[Hijos',
        ),
        migrations.AlterModelTable(
            name='histestados',
            table='Censo].[HistEstados',
        ),
        migrations.AlterModelTable(
            name='municipios',
            table='Censo].[Municipios',
        ),
        migrations.AlterModelTable(
            name='prestamos',
            table='Censo].[Prestamos',
        ),
        migrations.AlterModelTable(
            name='profesionoficio',
            table='Censo].[ProfesionOficio',
        ),
    ]
